name: echo_note
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flashy_tab_bar2: ^0.0.6
  intl: ^0.19.0
  speech_to_text: ^6.6.2
  avatar_glow: ^3.0.1
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  assets:
    - assets/icons/doc_icon_off.png
    - assets/icons/favourite_icon_off.png
    - assets/icons/save_icon.png
    - assets/icons/search.png
    - assets/icons/trash.png
    - assets/icons/edit.png

